In [1]:
import torch

In [4]:
one_d = torch.arange(0,9)
one_d 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
print('cantidad de dimensiones:', two_d.dim())

cantidad de dimensiones: 2


In [10]:
x = torch.arange(18).view(3,2,3)
print(x)


tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])
