In [1]:
import torch

In [3]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)

print(mat_a)
print(mat_b)


tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [4]:
mul = torch.matmul(mat_a, mat_b)
print(mul)

tensor([[ 29, -16],
        [ 38,   6]])


In [5]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])